language: node_js
node_js:
  - 12

services:
  - docker

# Pre-testing installs
install:
  - docker-compose -f deployment/docker/docker-compose-build.prod.yaml build --parallel

deploy:
  - provider: script
    script: bash deployment/docker/publish.sh
    on:
      branch: master

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push swilliams13/udagram